const algorithms = [
    {
        id: 'binary-search',
        name: 'Binary Search',
        category: 'Searching',
        difficulty: 'Easy',
        time: 'O(log n)',
        description: 'Efficiently find a target value in a sorted array by repeatedly dividing the search interval in half.',
        keywords: ['binary search', 'search', 'sorted array', 'divide and conquer', 'half'],
        vizType: 'array',
        vizData: [2, 5, 8, 12, 16, 23, 38, 45, 56, 72, 91],
        target: 23,
        code: {
            python: [
                { text: 'def binary_search(arr, target):', tokens: [{type:'keyword',val:'def'},{type:'function',val:' binary_search'},{type:'operator',val:'('},{type:'param',val:'arr'},{type:'operator',val:', '},{type:'param',val:'target'},{type:'operator',val:'):'}] },
                { text: '    left, right = 0, len(arr) - 1', tokens: [{type:'variable',val:'    left'},{type:'operator',val:', '},{type:'variable',val:'right'},{type:'operator',val:' = '},{type:'number',val:'0'},{type:'operator',val:', '},{type:'builtin',val:'len'},{type:'operator',val:'('},{type:'variable',val:'arr'},{type:'operator',val:') - '},{type:'number',val:'1'}] },
                { text: '    while left <= right:', tokens: [{type:'keyword',val:'    while '},{type:'variable',val:'left'},{type:'operator',val:' <= '},{type:'variable',val:'right'},{type:'operator',val:':'}] },
                { text: '        mid = (left + right) // 2', tokens: [{type:'variable',val:'        mid'},{type:'operator',val:' = ('},{type:'variable',val:'left'},{type:'operator',val:' + '},{type:'variable',val:'right'},{type:'operator',val:') // '},{type:'number',val:'2'}] },
                { text: '        if arr[mid] == target:', tokens: [{type:'keyword',val:'        if '},{type:'variable',val:'arr'},{type:'operator',val:'['},{type:'variable',val:'mid'},{type:'operator',val:'] == '},{type:'param',val:'target'},{type:'operator',val:':'}] },
                { text: '            return mid', tokens: [{type:'keyword',val:'            return '},{type:'variable',val:'mid'}] },
                { text: '        elif arr[mid] < target:', tokens: [{type:'keyword',val:'        elif '},{type:'variable',val:'arr'},{type:'operator',val:'['},{type:'variable',val:'mid'},{type:'operator',val:'] < '},{type:'param',val:'target'},{type:'operator',val:':'}] },
                { text: '            left = mid + 1', tokens: [{type:'variable',val:'            left'},{type:'operator',val:' = '},{type:'variable',val:'mid'},{type:'operator',val:' + '},{type:'number',val:'1'}] },
                { text: '        else:', tokens: [{type:'keyword',val:'        else:'}] },
                { text: '            right = mid - 1', tokens: [{type:'variable',val:'            right'},{type:'operator',val:' = '},{type:'variable',val:'mid'},{type:'operator',val:' - '},{type:'number',val:'1'}] },
                { text: '    return -1', tokens: [{type:'keyword',val:'    return '},{type:'number',val:'-1'}] },
            ],
            javascript: [
                { text: 'function binarySearch(arr, target) {', tokens: [{type:'keyword',val:'function'},{type:'function',val:' binarySearch'},{type:'operator',val:'('},{type:'param',val:'arr'},{type:'operator',val:', '},{type:'param',val:'target'},{type:'operator',val:') {'}] },
                { text: '    let left = 0, right = arr.length - 1;', tokens: [{type:'keyword',val:'    let '},{type:'variable',val:'left'},{type:'operator',val:' = '},{type:'number',val:'0'},{type:'operator',val:', '},{type:'variable',val:'right'},{type:'operator',val:' = '},{type:'variable',val:'arr'},{type:'operator',val:'.length - '},{type:'number',val:'1'},{type:'operator',val:';'}] },
                { text: '    while (left <= right) {', tokens: [{type:'keyword',val:'    while '},{type:'operator',val:'('},{type:'variable',val:'left'},{type:'operator',val:' <= '},{type:'variable',val:'right'},{type:'operator',val:') {'}] },
                { text: '        let mid = Math.floor((left + right) / 2);', tokens: [{type:'keyword',val:'        let '},{type:'variable',val:'mid'},{type:'operator',val:' = '},{type:'type',val:'Math'},{type:'method',val:'.floor'},{type:'operator',val:'(('},{type:'variable',val:'left'},{type:'operator',val:' + '},{type:'variable',val:'right'},{type:'operator',val:') / '},{type:'number',val:'2'},{type:'operator',val:');'}] },
                { text: '        if (arr[mid] === target) {', tokens: [{type:'keyword',val:'        if '},{type:'operator',val:'('},{type:'variable',val:'arr'},{type:'operator',val:'['},{type:'variable',val:'mid'},{type:'operator',val:'] === '},{type:'param',val:'target'},{type:'operator',val:') {'}] },
                { text: '            return mid;', tokens: [{type:'keyword',val:'            return '},{type:'variable',val:'mid'},{type:'operator',val:';'}] },
                { text: '        } else if (arr[mid] < target) {', tokens: [{type:'keyword',val:'        } else if '},{type:'operator',val:'('},{type:'variable',val:'arr'},{type:'operator',val:'['},{type:'variable',val:'mid'},{type:'operator',val:'] < '},{type:'param',val:'target'},{type:'operator',val:') {'}] },
                { text: '            left = mid + 1;', tokens: [{type:'variable',val:'            left'},{type:'operator',val:' = '},{type:'variable',val:'mid'},{type:'operator',val:' + '},{type:'number',val:'1'},{type:'operator',val:';'}] },
                { text: '        } else {', tokens: [{type:'keyword',val:'        } else {'}] },
                { text: '            right = mid - 1;', tokens: [{type:'variable',val:'            right'},{type:'operator',val:' = '},{type:'variable',val:'mid'},{type:'operator',val:' - '},{type:'number',val:'1'},{type:'operator',val:';'}] },
                { text: '        }', tokens: [{type:'operator',val:'        }'}] },
                { text: '    }', tokens: [{type:'operator',val:'    }'}] },
                { text: '    return -1;', tokens: [{type:'keyword',val:'    return '},{type:'number',val:'-1'},{type:'operator',val:';'}] },
                { text: '}', tokens: [{type:'operator',val:'}'}] },
            ],
            java: [
                { text: 'public int binarySearch(int[] arr, int target) {', tokens: [{type:'keyword',val:'public int'},{type:'function',val:' binarySearch'},{type:'operator',val:'('},{type:'type',val:'int'},{type:'operator',val:'[] '},{type:'param',val:'arr'},{type:'operator',val:', '},{type:'type',val:'int '},{type:'param',val:'target'},{type:'operator',val:') {'}] },
                { text: '    int left = 0, right = arr.length - 1;', tokens: [{type:'keyword',val:'    int '},{type:'variable',val:'left'},{type:'operator',val:' = '},{type:'number',val:'0'},{type:'operator',val:', '},{type:'variable',val:'right'},{type:'operator',val:' = '},{type:'variable',val:'arr'},{type:'operator',val:'.length - '},{type:'number',val:'1'},{type:'operator',val:';'}] },
                { text: '    while (left <= right) {', tokens: [{type:'keyword',val:'    while '},{type:'operator',val:'('},{type:'variable',val:'left'},{type:'operator',val:' <= '},{type:'variable',val:'right'},{type:'operator',val:') {'}] },
                { text: '        int mid = left + (right - left) / 2;', tokens: [{type:'keyword',val:'        int '},{type:'variable',val:'mid'},{type:'operator',val:' = '},{type:'variable',val:'left'},{type:'operator',val:' + ('},{type:'variable',val:'right'},{type:'operator',val:' - '},{type:'variable',val:'left'},{type:'operator',val:') / '},{type:'number',val:'2'},{type:'operator',val:';'}] },
                { text: '        if (arr[mid] == target) {', tokens: [{type:'keyword',val:'        if '},{type:'operator',val:'('},{type:'variable',val:'arr'},{type:'operator',val:'['},{type:'variable',val:'mid'},{type:'operator',val:'] == '},{type:'param',val:'target'},{type:'operator',val:') {'}] },
                { text: '            return mid;', tokens: [{type:'keyword',val:'            return '},{type:'variable',val:'mid'},{type:'operator',val:';'}] },
                { text: '        } else if (arr[mid] < target) {', tokens: [{type:'keyword',val:'        } else if '},{type:'operator',val:'('},{type:'variable',val:'arr'},{type:'operator',val:'['},{type:'variable',val:'mid'},{type:'operator',val:'] < '},{type:'param',val:'target'},{type:'operator',val:') {'}] },
                { text: '            left = mid + 1;', tokens: [{type:'variable',val:'            left'},{type:'operator',val:' = '},{type:'variable',val:'mid'},{type:'operator',val:' + '},{type:'number',val:'1'},{type:'operator',val:';'}] },
                { text: '        } else {', tokens: [{type:'keyword',val:'        } else {'}] },
                { text: '            right = mid - 1;', tokens: [{type:'variable',val:'            right'},{type:'operator',val:' = '},{type:'variable',val:'mid'},{type:'operator',val:' - '},{type:'number',val:'1'},{type:'operator',val:';'}] },
                { text: '        }', tokens: [{type:'operator',val:'        }'}] },
                { text: '    }', tokens: [{type:'operator',val:'    }'}] },
                { text: '    return -1;', tokens: [{type:'keyword',val:'    return '},{type:'number',val:'-1'},{type:'operator',val:';'}] },
                { text: '}', tokens: [{type:'operator',val:'}'}] },
            ]
        }
    },
    {
        id: 'two-sum',
        name: 'Two Sum',
        category: 'Arrays',
        difficulty: 'Easy',
        time: 'O(n)',
        description: 'Find two numbers in an array that add up to a target value and return their indices.',
        keywords: ['two sum', 'pair sum', 'array', 'hash map', 'indices', 'add up', 'target sum'],
        vizType: 'array-pair',
        vizData: [2, 7, 11, 15, 3, 6],
        target: 9,
        code: {
            python: [
                { text: 'def two_sum(nums, target):', tokens: [{type:'keyword',val:'def'},{type:'function',val:' two_sum'},{type:'operator',val:'('},{type:'param',val:'nums'},{type:'operator',val:', '},{type:'param',val:'target'},{type:'operator',val:'):'}] },
                { text: '    seen = {}', tokens: [{type:'variable',val:'    seen'},{type:'operator',val:' = {'},{type:'operator',val:'}'}] },
                { text: '    for i, num in enumerate(nums):', tokens: [{type:'keyword',val:'    for '},{type:'variable',val:'i'},{type:'operator',val:', '},{type:'variable',val:'num'},{type:'keyword',val:' in '},{type:'builtin',val:'enumerate'},{type:'operator',val:'('},{type:'variable',val:'nums'},{type:'operator',val:'):'}] },
                { text: '        complement = target - num', tokens: [{type:'variable',val:'        complement'},{type:'operator',val:' = '},{type:'param',val:'target'},{type:'operator',val:' - '},{type:'variable',val:'num'}] },
                { text: '        if complement in seen:', tokens: [{type:'keyword',val:'        if '},{type:'variable',val:'complement'},{type:'keyword',val:' in '},{type:'variable',val:'seen'},{type:'operator',val:':'}] },
                { text: '            return [seen[complement], i]', tokens: [{type:'keyword',val:'            return '},{type:'operator',val:'['},{type:'variable',val:'seen'},{type:'operator',val:'['},{type:'variable',val:'complement'},{type:'operator',val:']'},{type:'operator',val:', '},{type:'variable',val:'i'},{type:'operator',val:']'}] },
                { text: '        seen[num] = i', tokens: [{type:'variable',val:'        seen'},{type:'operator',val:'['},{type:'variable',val:'num'},{type:'operator',val:'] = '},{type:'variable',val:'i'}] },
                { text: '    return []', tokens: [{type:'keyword',val:'    return '},{type:'operator',val:'[]'}] },
            ],
            javascript: [
                { text: 'function twoSum(nums, target) {', tokens: [{type:'keyword',val:'function'},{type:'function',val:' twoSum'},{type:'operator',val:'('},{type:'param',val:'nums'},{type:'operator',val:', '},{type:'param',val:'target'},{type:'operator',val:') {'}] },
                { text: '    const seen = {};', tokens: [{type:'keyword',val:'    const '},{type:'variable',val:'seen'},{type:'operator',val:' = {'},{type:'operator',val:'};'}] },
                { text: '    for (let i = 0; i < nums.length; i++) {', tokens: [{type:'keyword',val:'    for '},{type:'operator',val:'('},{type:'keyword',val:'let '},{type:'variable',val:'i'},{type:'operator',val:' = '},{type:'number',val:'0'},{type:'operator',val:'; '},{type:'variable',val:'i'},{type:'operator',val:' < '},{type:'variable',val:'nums'},{type:'operator',val:'.length; '},{type:'variable',val:'i'},{type:'operator',val:'++) {'}] },
                { text: '        const complement = target - nums[i];', tokens: [{type:'keyword',val:'        const '},{type:'variable',val:'complement'},{type:'operator',val:' = '},{type:'param',val:'target'},{type:'operator',val:' - '},{type:'variable',val:'nums'},{type:'operator',val:'['},{type:'variable',val:'i'},{type:'operator',val:'];'}] },
                { text: '        if (complement in seen) {', tokens: [{type:'keyword',val:'        if '},{type:'operator',val:'('},{type:'variable',val:'complement'},{type:'keyword',val:' in '},{type:'variable',val:'seen'},{type:'operator',val:') {'}] },
                { text: '            return [seen[complement], i];', tokens: [{type:'keyword',val:'            return '},{type:'operator',val:'['},{type:'variable',val:'seen'},{type:'operator',val:'['},{type:'variable',val:'complement'},{type:'operator',val:']'},{type:'operator',val:', '},{type:'variable',val:'i'},{type:'operator',val:'];'}] },
                { text: '        }', tokens: [{type:'operator',val:'        }'}] },
                { text: '        seen[nums[i]] = i;', tokens: [{type:'variable',val:'        seen'},{type:'operator',val:'['},{type:'variable',val:'nums'},{type:'operator',val:'['},{type:'variable',val:'i'},{type:'operator',val:']] = '},{type:'variable',val:'i'},{type:'operator',val:';'}] },
                { text: '    }', tokens: [{type:'operator',val:'    }'}] },
                { text: '    return [];', tokens: [{type:'keyword',val:'    return '},{type:'operator',val:'[];'}] },
                { text: '}', tokens: [{type:'operator',val:'}'}] },
            ],
            java: [
                { text: 'public int[] twoSum(int[] nums, int target) {', tokens: [{type:'keyword',val:'public int'},{type:'operator',val:'[]'},{type:'function',val:' twoSum'},{type:'operator',val:'('},{type:'type',val:'int'},{type:'operator',val:'[] '},{type:'param',val:'nums'},{type:'operator',val:', '},{type:'type',val:'int '},{type:'param',val:'target'},{type:'operator',val:') {'}] },
                { text: '    Map<Integer, Integer> seen = new HashMap<>();', tokens: [{type:'keyword',val:'    Map'},{type:'operator',val:'<'},{type:'type',val:'Integer'},{type:'operator',val:', '},{type:'type',val:'Integer'},{type:'operator',val:'> '},{type:'variable',val:'seen'},{type:'operator',val:' = '},{type:'keyword',val:'new '},{type:'type',val:'HashMap'},{type:'operator',val:'<>();'}] },
                { text: '    for (int i = 0; i < nums.length; i++) {', tokens: [{type:'keyword',val:'    for '},{type:'operator',val:'('},{type:'type',val:'int '},{type:'variable',val:'i'},{type:'operator',val:' = '},{type:'number',val:'0'},{type:'operator',val:'; '},{type:'variable',val:'i'},{type:'operator',val:' < '},{type:'variable',val:'nums'},{type:'operator',val:'.length; '},{type:'variable',val:'i'},{type:'operator',val:'++) {'}] },
                { text: '        int complement = target - nums[i];', tokens: [{type:'keyword',val:'        int '},{type:'variable',val:'complement'},{type:'operator',val:' = '},{type:'param',val:'target'},{type:'operator',val:' - '},{type:'variable',val:'nums'},{type:'operator',val:'['},{type:'variable',val:'i'},{type:'operator',val:'];'}] },
                { text: '        if (seen.containsKey(complement)) {', tokens: [{type:'keyword',val:'        if '},{type:'operator',val:'('},{type:'variable',val:'seen'},{type:'method',val:'.containsKey'},{type:'operator',val:'('},{type:'variable',val:'complement'},{type:'operator',val:')) {'}] },
                { text: '            return new int[]{seen.get(complement), i};', tokens: [{type:'keyword',val:'            return '},{type:'keyword',val:'new '},{type:'type',val:'int'},{type:'operator',val:'[]{'},{type:'variable',val:'seen'},{type:'method',val:'.get'},{type:'operator',val:'('},{type:'variable',val:'complement'},{type:'operator',val:')'},{type:'operator',val:', '},{type:'variable',val:'i'},{type:'operator',val:'};'}] },
                { text: '        }', tokens: [{type:'operator',val:'        }'}] },
                { text: '        seen.put(nums[i], i);', tokens: [{type:'variable',val:'        seen'},{type:'method',val:'.put'},{type:'operator',val:'('},{type:'variable',val:'nums'},{type:'operator',val:'['},{type:'variable',val:'i'},{type:'operator',val:'], '},{type:'variable',val:'i'},{type:'operator',val:');'}] },
                { text: '    }', tokens: [{type:'operator',val:'    }'}] },
                { text: '    return new int[]{};', tokens: [{type:'keyword',val:'    return '},{type:'keyword',val:'new '},{type:'type',val:'int'},{type:'operator',val:'[]{'},{type:'operator',val:'};'}] },
                { text: '}', tokens: [{type:'operator',val:'}'}] },
            ]
        }
    },
    {
        id: 'bubble-sort',
        name: 'Bubble Sort',
        category: 'Sorting',
        difficulty: 'Easy',
        time: 'O(n²)',
        description: 'Repeatedly step through the list, compare adjacent elements, and swap them if they are in the wrong order.',
        keywords: ['bubble sort', 'sort', 'swap', 'adjacent', 'comparison', 'ordering'],
        vizType: 'sort',
        vizData: [64, 34, 25, 12, 22, 11, 90],
        code: {
            python: [
                { text: 'def bubble_sort(arr):', tokens: [{type:'keyword',val:'def'},{type:'function',val:' bubble_sort'},{type:'operator',val:'('},{type:'param',val:'arr'},{type:'operator',val:'):'}] },
                { text: '    n = len(arr)', tokens: [{type:'variable',val:'    n'},{type:'operator',val:' = '},{type:'builtin',val:'len'},{type:'operator',val:'('},{type:'variable',val:'arr'},{type:'operator',val:')'}] },
                { text: '    for i in range(n):', tokens: [{type:'keyword',val:'    for '},{type:'variable',val:'i'},{type:'keyword',val:' in '},{type:'builtin',val:'range'},{type:'operator',val:'('},{type:'variable',val:'n'},{type:'operator',val:'):'}] },
                { text: '        for j in range(0, n - i - 1):', tokens: [{type:'keyword',val:'        for '},{type:'variable',val:'j'},{type:'keyword',val:' in '},{type:'builtin',val:'range'},{type:'operator',val:'('},{type:'number',val:'0'},{type:'operator',val:', '},{type:'variable',val:'n'},{type:'operator',val:' - '},{type:'variable',val:'i'},{type:'operator',val:' - '},{type:'number',val:'1'},{type:'operator',val:'):'}] },
                { text: '            if arr[j] > arr[j + 1]:', tokens: [{type:'keyword',val:'            if '},{type:'variable',val:'arr'},{type:'operator',val:'['},{type:'variable',val:'j'},{type:'operator',val:'] > '},{type:'variable',val:'arr'},{type:'operator',val:'['},{type:'variable',val:'j'},{type:'operator',val:' + '},{type:'number',val:'1'},{type:'operator',val:']:'}] },
                { text: '                arr[j], arr[j+1] = arr[j+1], arr[j]', tokens: [{type:'variable',val:'                arr'},{type:'operator',val:'['},{type:'variable',val:'j'},{type:'operator',val:']'},{type:'operator',val:', '},{type:'variable',val:'arr'},{type:'operator',val:'['},{type:'variable',val:'j'},{type:'operator',val:'+1] = '},{type:'variable',val:'arr'},{type:'operator',val:'['},{type:'variable',val:'j'},{type:'operator',val:'+1], '},{type:'variable',val:'arr'},{type:'operator',val:'['},{type:'variable',val:'j'},{type:'operator',val:']'}] },
                { text: '    return arr', tokens: [{type:'keyword',val:'    return '},{type:'variable',val:'arr'}] },
            ],
            javascript: [
                { text: 'function bubbleSort(arr) {', tokens: [{type:'keyword',val:'function'},{type:'function',val:' bubbleSort'},{type:'operator',val:'('},{type:'param',val:'arr'},{type:'operator',val:') {'}] },
                { text: '    const n = arr.length;', tokens: [{type:'keyword',val:'    const '},{type:'variable',val:'n'},{type:'operator',val:' = '},{type:'variable',val:'arr'},{type:'operator',val:'.length;'}] },
                { text: '    for (let i = 0; i < n; i++) {', tokens: [{type:'keyword',val:'    for '},{type:'operator',val:'('},{type:'keyword',val:'let '},{type:'variable',val:'i'},{type:'operator',val:' = '},{type:'number',val:'0'},{type:'operator',val:'; '},{type:'variable',val:'i'},{type:'operator',val:' < '},{type:'variable',val:'n'},{type:'operator',val:'; '},{type:'variable',val:'i'},{type:'operator',val:'++) {'}] },
                { text: '        for (let j = 0; j < n - i - 1; j++) {', tokens: [{type:'keyword',val:'        for '},{type:'operator',val:'('},{type:'keyword',val:'let '},{type:'variable',val:'j'},{type:'operator',val:' = '},{type:'number',val:'0'},{type:'operator',val:'; '},{type:'variable',val:'j'},{type:'operator',val:' < '},{type:'variable',val:'n'},{type:'operator',val:' - '},{type:'variable',val:'i'},{type:'operator',val:' - '},{type:'number',val:'1'},{type:'operator',val:'; '},{type:'variable',val:'j'},{type:'operator',val:'++) {'}] },
                { text: '            if (arr[j] > arr[j + 1]) {', tokens: [{type:'keyword',val:'            if '},{type:'operator',val:'('},{type:'variable',val:'arr'},{type:'operator',val:'['},{type:'variable',val:'j'},{type:'operator',val:'] > '},{type:'variable',val:'arr'},{type:'operator',val:'['},{type:'variable',val:'j'},{type:'operator',val:' + '},{type:'number',val:'1'},{type:'operator',val:']) {'}] },
                { text: '                [arr[j], arr[j+1]] = [arr[j+1], arr[j]];', tokens: [{type:'operator',val:'                ['},{type:'variable',val:'arr'},{type:'operator',val:'['},{type:'variable',val:'j'},{type:'operator',val:']'},{type:'operator',val:', '},{type:'variable',val:'arr'},{type:'operator',val:'['},{type:'variable',val:'j'},{type:'operator',val:'+1]] = ['},{type:'variable',val:'arr'},{type:'operator',val:'['},{type:'variable',val:'j'},{type:'operator',val:'+1]'},{type:'operator',val:', '},{type:'variable',val:'arr'},{type:'operator',val:'['},{type:'variable',val:'j'},{type:'operator',val:']];'}] },
                { text: '            }', tokens: [{type:'operator',val:'            }'}] },
                { text: '        }', tokens: [{type:'operator',val:'        }'}] },
                { text: '    }', tokens: [{type:'operator',val:'    }'}] },
                { text: '    return arr;', tokens: [{type:'keyword',val:'    return '},{type:'variable',val:'arr'},{type:'operator',val:';'}] },
                { text: '}', tokens: [{type:'operator',val:'}'}] },
            ],
            java: [
                { text: 'public void bubbleSort(int[] arr) {', tokens: [{type:'keyword',val:'public void'},{type:'function',val:' bubbleSort'},{type:'operator',val:'('},{type:'type',val:'int'},{type:'operator',val:'[] '},{type:'param',val:'arr'},{type:'operator',val:') {'}] },
                { text: '    int n = arr.length;', tokens: [{type:'keyword',val:'    int '},{type:'variable',val:'n'},{type:'operator',val:' = '},{type:'variable',val:'arr'},{type:'operator',val:'.length;'}] },
                { text: '    for (int i = 0; i < n; i++) {', tokens: [{type:'keyword',val:'    for '},{type:'operator',val:'('},{type:'type',val:'int '},{type:'variable',val:'i'},{type:'operator',val:' = '},{type:'number',val:'0'},{type:'operator',val:'; '},{type:'variable',val:'i'},{type:'operator',val:' < '},{type:'variable',val:'n'},{type:'operator',val:'; '},{type:'variable',val:'i'},{type:'operator',val:'++) {'}] },
                { text: '        for (int j = 0; j < n - i - 1; j++) {', tokens: [{type:'keyword',val:'        for '},{type:'operator',val:'('},{type:'type',val:'int '},{type:'variable',val:'j'},{type:'operator',val:' = '},{type:'number',val:'0'},{type:'operator',val:'; '},{type:'variable',val:'j'},{type:'operator',val:' < '},{type:'variable',val:'n'},{type:'operator',val:' - '},{type:'variable',val:'i'},{type:'operator',val:' - '},{type:'number',val:'1'},{type:'operator',val:'; '},{type:'variable',val:'j'},{type:'operator',val:'++) {'}] },
                { text: '            if (arr[j] > arr[j + 1]) {', tokens: [{type:'keyword',val:'            if '},{type:'operator',val:'('},{type:'variable',val:'arr'},{type:'operator',val:'['},{type:'variable',val:'j'},{type:'operator',val:'] > '},{type:'variable',val:'arr'},{type:'operator',val:'['},{type:'variable',val:'j'},{type:'operator',val:' + '},{type:'number',val:'1'},{type:'operator',val:']) {'}] },
                { text: '                int temp = arr[j];', tokens: [{type:'keyword',val:'                int '},{type:'variable',val:'temp'},{type:'operator',val:' = '},{type:'variable',val:'arr'},{type:'operator',val:'['},{type:'variable',val:'j'},{type:'operator',val:'];'}] },
                { text: '                arr[j] = arr[j + 1];', tokens: [{type:'variable',val:'                arr'},{type:'operator',val:'['},{type:'variable',val:'j'},{type:'operator',val:'] = '},{type:'variable',val:'arr'},{type:'operator',val:'['},{type:'variable',val:'j'},{type:'operator',val:' + '},{type:'number',val:'1'},{type:'operator',val:'];'}] },
                { text: '                arr[j + 1] = temp;', tokens: [{type:'variable',val:'                arr'},{type:'operator',val:'['},{type:'variable',val:'j'},{type:'operator',val:' + '},{type:'number',val:'1'},{type:'operator',val:'] = '},{type:'variable',val:'temp'},{type:'operator',val:';'}] },
                { text: '            }', tokens: [{type:'operator',val:'            }'}] },
                { text: '        }', tokens: [{type:'operator',val:'        }'}] },
                { text: '    }', tokens: [{type:'operator',val:'    }'}] },
                { text: '}', tokens: [{type:'operator',val:'}'}] },
            ]
        }
    },
    {
        id: 'fibonacci',
        name: 'Fibonacci Sequence',
        category: 'Recursion',
        difficulty: 'Easy',
        time: 'O(2^n)',
        description: 'Generate the Fibonacci sequence where each number is the sum of the two preceding ones.',
        keywords: ['fibonacci', 'recursion', 'recursive', 'sequence', 'series', 'sum', 'preceding'],
        vizType: 'tree',
        vizData: [5],
        code: {
            python: [
                { text: 'def fibonacci(n):', tokens: [{type:'keyword',val:'def'},{type:'function',val:' fibonacci'},{type:'operator',val:'('},{type:'param',val:'n'},{type:'operator',val:'):'}] },
                { text: '    if n <= 1:', tokens: [{type:'keyword',val:'    if '},{type:'variable',val:'n'},{type:'operator',val:' <= '},{type:'number',val:'1'},{type:'operator',val:':'}] },
                { text: '        return n', tokens: [{type:'keyword',val:'        return '},{type:'variable',val:'n'}] },
                { text: '    return fibonacci(n-1) + fibonacci(n-2)', tokens: [{type:'keyword',val:'    return '},{type:'function',val:'fibonacci'},{type:'operator',val:'('},{type:'variable',val:'n'},{type:'operator',val:'-1) + '},{type:'function',val:'fibonacci'},{type:'operator',val:'('},{type:'variable',val:'n'},{type:'operator',val:'-2)'}] },
            ],
            javascript: [
                { text: 'function fibonacci(n) {', tokens: [{type:'keyword',val:'function'},{type:'function',val:' fibonacci'},{type:'operator',val:'('},{type:'param',val:'n'},{type:'operator',val:') {'}] },
                { text: '    if (n <= 1) return n;', tokens: [{type:'keyword',val:'    if '},{type:'operator',val:'('},{type:'variable',val:'n'},{type:'operator',val:' <= '},{type:'number',val:'1'},{type:'operator',val:') return '},{type:'variable',val:'n'},{type:'operator',val:';'}] },
                { text: '    return fibonacci(n - 1) + fibonacci(n - 2);', tokens: [{type:'keyword',val:'    return '},{type:'function',val:'fibonacci'},{type:'operator',val:'('},{type:'variable',val:'n'},{type:'operator',val:' - '},{type:'number',val:'1'},{type:'operator',val:') + '},{type:'function',val:'fibonacci'},{type:'operator',val:'('},{type:'variable',val:'n'},{type:'operator',val:' - '},{type:'number',val:'2'},{type:'operator',val:');'}] },
                { text: '}', tokens: [{type:'operator',val:'}'}] },
            ],
            java: [
                { text: 'public int fibonacci(int n) {', tokens: [{type:'keyword',val:'public int'},{type:'function',val:' fibonacci'},{type:'operator',val:'('},{type:'type',val:'int '},{type:'param',val:'n'},{type:'operator',val:') {'}] },
                { text: '    if (n <= 1) return n;', tokens: [{type:'keyword',val:'    if '},{type:'operator',val:'('},{type:'variable',val:'n'},{type:'operator',val:' <= '},{type:'number',val:'1'},{type:'operator',val:') return '},{type:'variable',val:'n'},{type:'operator',val:';'}] },
                { text: '    return fibonacci(n - 1) + fibonacci(n - 2);', tokens: [{type:'keyword',val:'    return '},{type:'function',val:'fibonacci'},{type:'operator',val:'('},{type:'variable',val:'n'},{type:'operator',val:' - '},{type:'number',val:'1'},{type:'operator',val:') + '},{type:'function',val:'fibonacci'},{type:'operator',val:'('},{type:'variable',val:'n'},{type:'operator',val:' - '},{type:'number',val:'2'},{type:'operator',val:');'}] },
                { text: '}', tokens: [{type:'operator',val:'}'}] },
            ]
        }
    },
    {
        id: 'linear-search',
        name: 'Linear Search',
        category: 'Searching',
        difficulty: 'Easy',
        time: 'O(n)',
        description: 'Sequentially check each element in a list until the target is found or the list is exhausted.',
        keywords: ['linear search', 'sequential search', 'search', 'find', 'scan'],
        vizType: 'array',
        vizData: [10, 23, 45, 70, 11, 15, 88, 42],
        target: 70,
        code: {
            python: [
                { text: 'def linear_search(arr, target):', tokens: [{type:'keyword',val:'def'},{type:'function',val:' linear_search'},{type:'operator',val:'('},{type:'param',val:'arr'},{type:'operator',val:', '},{type:'param',val:'target'},{type:'operator',val:'):'}] },
                { text: '    for i in range(len(arr)):', tokens: [{type:'keyword',val:'    for '},{type:'variable',val:'i'},{type:'keyword',val:' in '},{type:'builtin',val:'range'},{type:'operator',val:'('},{type:'builtin',val:'len'},{type:'operator',val:'('},{type:'variable',val:'arr'},{type:'operator',val:'):'},{type:'operator',val:')'}] },
                { text: '        if arr[i] == target:', tokens: [{type:'keyword',val:'        if '},{type:'variable',val:'arr'},{type:'operator',val:'['},{type:'variable',val:'i'},{type:'operator',val:'] == '},{type:'param',val:'target'},{type:'operator',val:':'}] },
                { text: '            return i', tokens: [{type:'keyword',val:'            return '},{type:'variable',val:'i'}] },
                { text: '    return -1', tokens: [{type:'keyword',val:'    return '},{type:'number',val:'-1'}] },
            ],
            javascript: [
                { text: 'function linearSearch(arr, target) {', tokens: [{type:'keyword',val:'function'},{type:'function',val:' linearSearch'},{type:'operator',val:'('},{type:'param',val:'arr'},{type:'operator',val:', '},{type:'param',val:'target'},{type:'operator',val:') {'}] },
                { text: '    for (let i = 0; i < arr.length; i++) {', tokens: [{type:'keyword',val:'    for '},{type:'operator',val:'('},{type:'keyword',val:'let '},{type:'variable',val:'i'},{type:'operator',val:' = '},{type:'number',val:'0'},{type:'operator',val:'; '},{type:'variable',val:'i'},{type:'operator',val:' < '},{type:'variable',val:'arr'},{type:'operator',val:'.length; '},{type:'variable',val:'i'},{type:'operator',val:'++) {'}] },
                { text: '        if (arr[i] === target) {', tokens: [{type:'keyword',val:'        if '},{type:'operator',val:'('},{type:'variable',val:'arr'},{type:'operator',val:'['},{type:'variable',val:'i'},{type:'operator',val:'] === '},{type:'param',val:'target'},{type:'operator',val:') {'}] },
                { text: '            return i;', tokens: [{type:'keyword',val:'            return '},{type:'variable',val:'i'},{type:'operator',val:';'}] },
                { text: '        }', tokens: [{type:'operator',val:'        }'}] },
                { text: '    }', tokens: [{type:'operator',val:'    }'}] },
                { text: '    return -1;', tokens: [{type:'keyword',val:'    return '},{type:'number',val:'-1'},{type:'operator',val:';'}] },
                { text: '}', tokens: [{type:'operator',val:'}'}] },
            ],
            java: [
                { text: 'public int linearSearch(int[] arr, int target) {', tokens: [{type:'keyword',val:'public int'},{type:'function',val:' linearSearch'},{type:'operator',val:'('},{type:'type',val:'int'},{type:'operator',val:'[] '},{type:'param',val:'arr'},{type:'operator',val:', '},{type:'type',val:'int '},{type:'param',val:'target'},{type:'operator',val:') {'}] },
                { text: '    for (int i = 0; i < arr.length; i++) {', tokens: [{type:'keyword',val:'    for '},{type:'operator',val:'('},{type:'type',val:'int '},{type:'variable',val:'i'},{type:'operator',val:' = '},{type:'number',val:'0'},{type:'operator',val:'; '},{type:'variable',val:'i'},{type:'operator',val:' < '},{type:'variable',val:'arr'},{type:'operator',val:'.length; '},{type:'variable',val:'i'},{type:'operator',val:'++) {'}] },
                { text: '        if (arr[i] == target) {', tokens: [{type:'keyword',val:'        if '},{type:'operator',val:'('},{type:'variable',val:'arr'},{type:'operator',val:'['},{type:'variable',val:'i'},{type:'operator',val:'] == '},{type:'param',val:'target'},{type:'operator',val:') {'}] },
                { text: '            return i;', tokens: [{type:'keyword',val:'            return '},{type:'variable',val:'i'},{type:'operator',val:';'}] },
                { text: '        }', tokens: [{type:'operator',val:'        }'}] },
                { text: '    }', tokens: [{type:'operator',val:'    }'}] },
                { text: '    return -1;', tokens: [{type:'keyword',val:'    return '},{type:'number',val:'-1'},{type:'operator',val:';'}] },
                { text: '}', tokens: [{type:'operator',val:'}'}] },
            ]
        }
    },
    {
        id: 'selection-sort',
        name: 'Selection Sort',
        category: 'Sorting',
        difficulty: 'Easy',
        time: 'O(n²)',
        description: 'Find the minimum element from the unsorted portion and place it at the beginning.',
        keywords: ['selection sort', 'sort', 'minimum', 'swap', 'ordering'],
        vizType: 'sort',
        vizData: [29, 10, 14, 37, 13],
        code: {
            python: [
                { text: 'def selection_sort(arr):', tokens: [{type:'keyword',val:'def'},{type:'function',val:' selection_sort'},{type:'operator',val:'('},{type:'param',val:'arr'},{type:'operator',val:'):'}] },
                { text: '    n = len(arr)', tokens: [{type:'variable',val:'    n'},{type:'operator',val:' = '},{type:'builtin',val:'len'},{type:'operator',val:'('},{type:'variable',val:'arr'},{type:'operator',val:')'}] },
                { text: '    for i in range(n):', tokens: [{type:'keyword',val:'    for '},{type:'variable',val:'i'},{type:'keyword',val:' in '},{type:'builtin',val:'range'},{type:'operator',val:'('},{type:'variable',val:'n'},{type:'operator',val:'):'}] },
                { text: '        min_idx = i', tokens: [{type:'variable',val:'        min_idx'},{type:'operator',val:' = '},{type:'variable',val:'i'}] },
                { text: '        for j in range(i+1, n):', tokens: [{type:'keyword',val:'        for '},{type:'variable',val:'j'},{type:'keyword',val:' in '},{type:'builtin',val:'range'},{type:'operator',val:'('},{type:'variable',val:'i'},{type:'operator',val:'+1, '},{type:'variable',val:'n'},{type:'operator',val:'):'}] },
                { text: '            if arr[j] < arr[min_idx]:', tokens: [{type:'keyword',val:'            if '},{type:'variable',val:'arr'},{type:'operator',val:'['},{type:'variable',val:'j'},{type:'operator',val:'] < '},{type:'variable',val:'arr'},{type:'operator',val:'['},{type:'variable',val:'min_idx'},{type:'operator',val:']:'}] },
                { text: '                min_idx = j', tokens: [{type:'variable',val:'                min_idx'},{type:'operator',val:' = '},{type:'variable',val:'j'}] },
                { text: '        arr[i], arr[min_idx] = arr[min_idx], arr[i]', tokens: [{type:'variable',val:'        arr'},{type:'operator',val:'['},{type:'variable',val:'i'},{type:'operator',val:']'},{type:'operator',val:', '},{type:'variable',val:'arr'},{type:'operator',val:'['},{type:'variable',val:'min_idx'},{type:'operator',val:'] = '},{type:'variable',val:'arr'},{type:'operator',val:'['},{type:'variable',val:'min_idx'},{type:'operator',val:']'},{type:'operator',val:', '},{type:'variable',val:'arr'},{type:'operator',val:'['},{type:'variable',val:'i'},{type:'operator',val:']'}] },
                { text: '    return arr', tokens: [{type:'keyword',val:'    return '},{type:'variable',val:'arr'}] },
            ],
            javascript: [
                { text: 'function selectionSort(arr) {', tokens: [{type:'keyword',val:'function'},{type:'function',val:' selectionSort'},{type:'operator',val:'('},{type:'param',val:'arr'},{type:'operator',val:') {'}] },
                { text: '    const n = arr.length;', tokens: [{type:'keyword',val:'    const '},{type:'variable',val:'n'},{type:'operator',val:' = '},{type:'variable',val:'arr'},{type:'operator',val:'.length;'}] },
                { text: '    for (let i = 0; i < n; i++) {', tokens: [{type:'keyword',val:'    for '},{type:'operator',val:'('},{type:'keyword',val:'let '},{type:'variable',val:'i'},{type:'operator',val:' = '},{type:'number',val:'0'},{type:'operator',val:'; '},{type:'variable',val:'i'},{type:'operator',val:' < '},{type:'variable',val:'n'},{type:'operator',val:'; '},{type:'variable',val:'i'},{type:'operator',val:'++) {'}] },
                { text: '        let minIdx = i;', tokens: [{type:'keyword',val:'        let '},{type:'variable',val:'minIdx'},{type:'operator',val:' = '},{type:'variable',val:'i'},{type:'operator',val:';'}] },
                { text: '        for (let j = i + 1; j < n; j++) {', tokens: [{type:'keyword',val:'        for '},{type:'operator',val:'('},{type:'keyword',val:'let '},{type:'variable',val:'j'},{type:'operator',val:' = '},{type:'variable',val:'i'},{type:'operator',val:' + '},{type:'number',val:'1'},{type:'operator',val:'; '},{type:'variable',val:'j'},{type:'operator',val:' < '},{type:'variable',val:'n'},{type:'operator',val:'; '},{type:'variable',val:'j'},{type:'operator',val:'++) {'}] },
                { text: '            if (arr[j] < arr[minIdx]) {', tokens: [{type:'keyword',val:'            if '},{type:'operator',val:'('},{type:'variable',val:'arr'},{type:'operator',val:'['},{type:'variable',val:'j'},{type:'operator',val:'] < '},{type:'variable',val:'arr'},{type:'operator',val:'['},{type:'variable',val:'minIdx'},{type:'operator',val:']) {'}] },
                { text: '                minIdx = j;', tokens: [{type:'variable',val:'                minIdx'},{type:'operator',val:' = '},{type:'variable',val:'j'},{type:'operator',val:';'}] },
                { text: '            }', tokens: [{type:'operator',val:'            }'}] },
                { text: '        }', tokens: [{type:'operator',val:'        }'}] },
                { text: '        [arr[i], arr[minIdx]] = [arr[minIdx], arr[i]];', tokens: [{type:'operator',val:'        ['},{type:'variable',val:'arr'},{type:'operator',val:'['},{type:'variable',val:'i'},{type:'operator',val:']'},{type:'operator',val:', '},{type:'variable',val:'arr'},{type:'operator',val:'['},{type:'variable',val:'minIdx'},{type:'operator',val:']] = ['},{type:'variable',val:'arr'},{type:'operator',val:'['},{type:'variable',val:'minIdx'},{type:'operator',val:']'},{type:'operator',val:', '},{type:'variable',val:'arr'},{type:'operator',val:'['},{type:'variable',val:'i'},{type:'operator',val:']];'}] },
                { text: '    }', tokens: [{type:'operator',val:'    }'}] },
                { text: '    return arr;', tokens: [{type:'keyword',val:'    return '},{type:'variable',val:'arr'},{type:'operator',val:';'}] },
                { text: '}', tokens: [{type:'operator',val:'}'}] },
            ],
            java: [
                { text: 'public void selectionSort(int[] arr) {', tokens: [{type:'keyword',val:'public void'},{type:'function',val:' selectionSort'},{type:'operator',val:'('},{type:'type',val:'int'},{type:'operator',val:'[] '},{type:'param',val:'arr'},{type:'operator',val:') {'}] },
                { text: '    int n = arr.length;', tokens: [{type:'keyword',val:'    int '},{type:'variable',val:'n'},{type:'operator',val:' = '},{type:'variable',val:'arr'},{type:'operator',val:'.length;'}] },
                { text: '    for (int i = 0; i < n; i++) {', tokens: [{type:'keyword',val:'    for '},{type:'operator',val:'('},{type:'type',val:'int '},{type:'variable',val:'i'},{type:'operator',val:' = '},{type:'number',val:'0'},{type:'operator',val:'; '},{type:'variable',val:'i'},{type:'operator',val:' < '},{type:'variable',val:'n'},{type:'operator',val:'; '},{type:'variable',val:'i'},{type:'operator',val:'++) {'}] },
                { text: '        int minIdx = i;', tokens: [{type:'keyword',val:'        int '},{type:'variable',val:'minIdx'},{type:'operator',val:' = '},{type:'variable',val:'i'},{type:'operator',val:';'}] },
                { text: '        for (int j = i + 1; j < n; j++) {', tokens: [{type:'keyword',val:'        for '},{type:'operator',val:'('},{type:'type',val:'int '},{type:'variable',val:'j'},{type:'operator',val:' = '},{type:'variable',val:'i'},{type:'operator',val:' + '},{type:'number',val:'1'},{type:'operator',val:'; '},{type:'variable',val:'j'},{type:'operator',val:' < '},{type:'variable',val:'n'},{type:'operator',val:'; '},{type:'variable',val:'j'},{type:'operator',val:'++) {'}] },
                { text: '            if (arr[j] < arr[minIdx]) {', tokens: [{type:'keyword',val:'            if '},{type:'operator',val:'('},{type:'variable',val:'arr'},{type:'operator',val:'['},{type:'variable',val:'j'},{type:'operator',val:'] < '},{type:'variable',val:'arr'},{type:'operator',val:'['},{type:'variable',val:'minIdx'},{type:'operator',val:']) {'}] },
                { text: '                minIdx = j;', tokens: [{type:'variable',val:'                minIdx'},{type:'operator',val:' = '},{type:'variable',val:'j'},{type:'operator',val:';'}] },
                { text: '            }', tokens: [{type:'operator',val:'            }'}] },
                { text: '        }', tokens: [{type:'operator',val:'        }'}] },
                { text: '        int temp = arr[i];', tokens: [{type:'keyword',val:'        int '},{type:'variable',val:'temp'},{type:'operator',val:' = '},{type:'variable',val:'arr'},{type:'operator',val:'['},{type:'variable',val:'i'},{type:'operator',val:'];'}] },
                { text: '        arr[i] = arr[minIdx];', tokens: [{type:'variable',val:'        arr'},{type:'operator',val:'['},{type:'variable',val:'i'},{type:'operator',val:'] = '},{type:'variable',val:'arr'},{type:'operator',val:'['},{type:'variable',val:'minIdx'},{type:'operator',val:'];'}] },
                { text: '        arr[minIdx] = temp;', tokens: [{type:'variable',val:'        arr'},{type:'operator',val:'['},{type:'variable',val:'minIdx'},{type:'operator',val:'] = '},{type:'variable',val:'temp'},{type:'operator',val:';'}] },
                { text: '    }', tokens: [{type:'operator',val:'    }'}] },
                { text: '}', tokens: [{type:'operator',val:'}'}] },
            ]
        }
    },
    {
        id: 'merge-sort',
        name: 'Merge Sort',
        category: 'Sorting',
        difficulty: 'Medium',
        time: 'O(n log n)',
        description: 'Divide the array into halves, recursively sort them, then merge the sorted halves.',
        keywords: ['merge sort', 'divide and conquer', 'sort', 'merge', 'recursive'],
        vizType: 'sort',
        vizData: [38, 27, 43, 3, 9, 82, 10],
        code: {
            python: [
                { text: 'def merge_sort(arr):', tokens: [{type:'keyword',val:'def'},{type:'function',val:' merge_sort'},{type:'operator',val:'('},{type:'param',val:'arr'},{type:'operator',val:'):'}] },
                { text: '    if len(arr) > 1:', tokens: [{type:'keyword',val:'    if '},{type:'builtin',val:'len'},{type:'operator',val:'('},{type:'variable',val:'arr'},{type:'operator',val:') > '},{type:'number',val:'1'}] },
                { text: '        mid = len(arr) // 2', tokens: [{type:'variable',val:'        mid'},{type:'operator',val:' = '},{type:'builtin',val:'len'},{type:'operator',val:'('},{type:'variable',val:'arr'},{type:'operator',val:') // '},{type:'number',val:'2'}] },
                { text: '        left = arr[:mid]', tokens: [{type:'variable',val:'        left'},{type:'operator',val:' = '},{type:'variable',val:'arr'},{type:'operator',val:':['},{type:'variable',val:'mid'},{type:'operator',val:']'}] },
                { text: '        right = arr[mid:]', tokens: [{type:'variable',val:'        right'},{type:'operator',val:' = '},{type:'variable',val:'arr'},{type:'operator',val:'['},{type:'variable',val:'mid'},{type:'operator',val:':]'}] },
                { text: '        merge_sort(left)', tokens: [{type:'function',val:'        merge_sort'},{type:'operator',val:'('},{type:'variable',val:'left'},{type:'operator',val:')'}] },
                { text: '        merge_sort(right)', tokens: [{type:'function',val:'        merge_sort'},{type:'operator',val:'('},{type:'variable',val:'right'},{type:'operator',val:')'}] },
                { text: '        # Merge logic here', tokens: [{type:'comment',val:'        # Merge logic here'}] },
                { text: '    return arr', tokens: [{type:'keyword',val:'    return '},{type:'variable',val:'arr'}] },
            ],
            javascript: [
                { text: 'function mergeSort(arr) {', tokens: [{type:'keyword',val:'function'},{type:'function',val:' mergeSort'},{type:'operator',val:'('},{type:'param',val:'arr'},{type:'operator',val:') {'}] },
                { text: '    if (arr.length > 1) {', tokens: [{type:'keyword',val:'    if '},{type:'operator',val:'('},{type:'variable',val:'arr'},{type:'operator',val:'.length > '},{type:'number',val:'1'},{type:'operator',val:') {'}] },
                { text: '        const mid = Math.floor(arr.length / 2);', tokens: [{type:'keyword',val:'        const '},{type:'variable',val:'mid'},{type:'operator',val:' = '},{type:'type',val:'Math'},{type:'method',val:'.floor'},{type:'operator',val:'('},{type:'variable',val:'arr'},{type:'operator',val:'.length / '},{type:'number',val:'2'},{type:'operator',val:');'}] },
                { text: '        const left = arr.slice(0, mid);', tokens: [{type:'keyword',val:'        const '},{type:'variable',val:'left'},{type:'operator',val:' = '},{type:'variable',val:'arr'},{type:'method',val:'.slice'},{type:'operator',val:'('},{type:'number',val:'0'},{type:'operator',val:', '},{type:'variable',val:'mid'},{type:'operator',val:');'}] },
                { text: '        const right = arr.slice(mid);', tokens: [{type:'keyword',val:'        const '},{type:'variable',val:'right'},{type:'operator',val:' = '},{type:'variable',val:'arr'},{type:'method',val:'.slice'},{type:'operator',val:'('},{type:'variable',val:'mid'},{type:'operator',val:');'}] },
                { text: '        mergeSort(left);', tokens: [{type:'function',val:'        mergeSort'},{type:'operator',val:'('},{type:'variable',val:'left'},{type:'operator',val:');'}] },
                { text: '        mergeSort(right);', tokens: [{type:'function',val:'        mergeSort'},{type:'operator',val:'('},{type:'variable',val:'right'},{type:'operator',val:');'}] },
                { text: '        // Merge logic here', tokens: [{type:'comment',val:'        // Merge logic here'}] },
                { text: '    }', tokens: [{type:'operator',val:'    }'}] },
                { text: '    return arr;', tokens: [{type:'keyword',val:'    return '},{type:'variable',val:'arr'},{type:'operator',val:';'}] },
                { text: '}', tokens: [{type:'operator',val:'}'}] },
            ],
            java: [
                { text: 'public void mergeSort(int[] arr, int l, int r) {', tokens: [{type:'keyword',val:'public void'},{type:'function',val:' mergeSort'},{type:'operator',val:'('},{type:'type',val:'int'},{type:'operator',val:'[] '},{type:'param',val:'arr'},{type:'operator',val:', '},{type:'type',val:'int '},{type:'param',val:'l'},{type:'operator',val:', '},{type:'type',val:'int '},{type:'param',val:'r'},{type:'operator',val:') {'}] },
                { text: '    if (l < r) {', tokens: [{type:'keyword',val:'    if '},{type:'operator',val:'('},{type:'variable',val:'l'},{type:'operator',val:' < '},{type:'variable',val:'r'},{type:'operator',val:') {'}] },
                { text: '        int mid = (l + r) / 2;', tokens: [{type:'keyword',val:'        int '},{type:'variable',val:'mid'},{type:'operator',val:' = ('},{type:'variable',val:'l'},{type:'operator',val:' + '},{type:'variable',val:'r'},{type:'operator',val:') / '},{type:'number',val:'2'},{type:'operator',val:';'}] },
                { text: '        mergeSort(arr, l, mid);', tokens: [{type:'function',val:'        mergeSort'},{type:'operator',val:'('},{type:'variable',val:'arr'},{type:'operator',val:', '},{type:'variable',val:'l'},{type:'operator',val:', '},{type:'variable',val:'mid'},{type:'operator',val:');'}] },
                { text: '        mergeSort(arr, mid + 1, r);', tokens: [{type:'function',val:'        mergeSort'},{type:'operator',val:'('},{type:'variable',val:'arr'},{type:'operator',val:', '},{type:'variable',val:'mid'},{type:'operator',val:' + '},{type:'number',val:'1'},{type:'operator',val:', '},{type:'variable',val:'r'},{type:'operator',val:');'}] },
                { text: '        // Merge logic here', tokens: [{type:'comment',val:'        // Merge logic here'}] },
                { text: '    }', tokens: [{type:'operator',val:'    }'}] },
                { text: '}', tokens: [{type:'operator',val:'}'}] },
            ]
        }
    },
    {
        id: 'reverse-linked-list',
        name: 'Reverse Linked List',
        category: 'Linked List',
        difficulty: 'Easy',
        time: 'O(n)',
        description: 'Reverse the direction of pointers in a singly linked list to reverse its order.',
        keywords: ['reverse', 'linked list', 'pointers', 'reversal', 'singly linked'],
        vizType: 'linkedlist',
        vizData: [1, 2, 3, 4, 5],
        code: {
            python: [
                { text: 'class ListNode:', tokens: [{type:'keyword',val:'class'},{type:'type',val:' ListNode'},{type:'operator',val:':'}] },
                { text: '    def __init__(self, val=0):', tokens: [{type:'keyword',val:'    def '},{type:'function',val:'__init__'},{type:'operator',val:'(self, val='},{type:'number',val:'0'},{type:'operator',val:'):'}] },
                { text: '        self.val = val', tokens: [{type:'variable',val:'        self.val'},{type:'operator',val:' = '},{type:'variable',val:'val'}] },
                { text: '        self.next = None', tokens: [{type:'variable',val:'        self.next'},{type:'operator',val:' = '},{type:'keyword',val:'None'}] },
                { text: '', tokens: [] },
                { text: 'def reverse_list(head):', tokens: [{type:'keyword',val:'def'},{type:'function',val:' reverse_list'},{type:'operator',val:'('},{type:'param',val:'head'},{type:'operator',val:'):'}] },
                { text: '    prev = None', tokens: [{type:'variable',val:'    prev'},{type:'operator',val:' = '},{type:'keyword',val:'None'}] },
                { text: '    curr = head', tokens: [{type:'variable',val:'    curr'},{type:'operator',val:' = '},{type:'variable',val:'head'}] },
                { text: '    while curr:', tokens: [{type:'keyword',val:'    while '},{type:'variable',val:'curr'},{type:'operator',val:':'}] },
                { text: '        next_temp = curr.next', tokens: [{type:'variable',val:'        next_temp'},{type:'operator',val:' = '},{type:'variable',val:'curr'},{type:'operator',val:'.next'}] },
                { text: '        curr.next = prev', tokens: [{type:'variable',val:'        curr.next'},{type:'operator',val:' = '},{type:'variable',val:'prev'}] },
                { text: '        prev = curr', tokens: [{type:'variable',val:'        prev'},{type:'operator',val:' = '},{type:'variable',val:'curr'}] },
                { text: '        curr = next_temp', tokens: [{type:'variable',val:'        curr'},{type:'operator',val:' = '},{type:'variable',val:'next_temp'}] },
                { text: '    return prev', tokens: [{type:'keyword',val:'    return '},{type:'variable',val:'prev'}] },
            ],
            javascript: [
                { text: 'function reverseList(head) {', tokens: [{type:'keyword',val:'function'},{type:'function',val:' reverseList'},{type:'operator',val:'('},{type:'param',val:'head'},{type:'operator',val:') {'}] },
                { text: '    let prev = null;', tokens: [{type:'keyword',val:'    let '},{type:'variable',val:'prev'},{type:'operator',val:' = '},{type:'keyword',val:'null'},{type:'operator',val:';'}] },
                { text: '    let curr = head;', tokens: [{type:'keyword',val:'    let '},{type:'variable',val:'curr'},{type:'operator',val:' = '},{type:'variable',val:'head'},{type:'operator',val:';'}] },
                { text: '    while (curr) {', tokens: [{type:'keyword',val:'    while '},{type:'operator',val:'('},{type:'variable',val:'curr'},{type:'operator',val:') {'}] },
                { text: '        let nextTemp = curr.next;', tokens: [{type:'keyword',val:'        let '},{type:'variable',val:'nextTemp'},{type:'operator',val:' = '},{type:'variable',val:'curr'},{type:'operator',val:'.next;'}] },
                { text: '        curr.next = prev;', tokens: [{type:'variable',val:'        curr.next'},{type:'operator',val:' = '},{type:'variable',val:'prev'},{type:'operator',val:';'}] },
                { text: '        prev = curr;', tokens: [{type:'variable',val:'        prev'},{type:'operator',val:' = '},{type:'variable',val:'curr'},{type:'operator',val:';'}] },
                { text: '        curr = nextTemp;', tokens: [{type:'variable',val:'        curr'},{type:'operator',val:' = '},{type:'variable',val:'nextTemp'},{type:'operator',val:';'}] },
                { text: '    }', tokens: [{type:'operator',val:'    }'}] },
                { text: '    return prev;', tokens: [{type:'keyword',val:'    return '},{type:'variable',val:'prev'},{type:'operator',val:';'}] },
                { text: '}', tokens: [{type:'operator',val:'}'}] },
            ],
            java: [
                { text: 'public ListNode reverseList(ListNode head) {', tokens: [{type:'keyword',val:'public '},{type:'type',val:'ListNode'},{type:'function',val:' reverseList'},{type:'operator',val:'('},{type:'type',val:'ListNode '},{type:'param',val:'head'},{type:'operator',val:') {'}] },
                { text: '    ListNode prev = null;', tokens: [{type:'type',val:'ListNode '},{type:'variable',val:'prev'},{type:'operator',val:' = '},{type:'keyword',val:'null'},{type:'operator',val:';'}] },
                { text: '    ListNode curr = head;', tokens: [{type:'type',val:'ListNode '},{type:'variable',val:'curr'},{type:'operator',val:' = '},{type:'variable',val:'head'},{type:'operator',val:';'}] },
                { text: '    while (curr != null) {', tokens: [{type:'keyword',val:'    while '},{type:'operator',val:'('},{type:'variable',val:'curr'},{type:'operator',val:' != '},{type:'keyword',val:'null'},{type:'operator',val:') {'}] },
                { text: '        ListNode nextTemp = curr.next;', tokens: [{type:'type',val:'ListNode '},{type:'variable',val:'nextTemp'},{type:'operator',val:' = '},{type:'variable',val:'curr'},{type:'operator',val:'.next;'}] },
                { text: '        curr.next = prev;', tokens: [{type:'variable',val:'        curr.next'},{type:'operator',val:' = '},{type:'variable',val:'prev'},{type:'operator',val:';'}] },
                { text: '        prev = curr;', tokens: [{type:'variable',val:'        prev'},{type:'operator',val:' = '},{type:'variable',val:'curr'},{type:'operator',val:';'}] },
                { text: '        curr = nextTemp;', tokens: [{type:'variable',val:'        curr'},{type:'operator',val:' = '},{type:'variable',val:'nextTemp'},{type:'operator',val:';'}] },
                { text: '    }', tokens: [{type:'operator',val:'    }'}] },
                { text: '    return prev;', tokens: [{type:'keyword',val:'    return '},{type:'variable',val:'prev'},{type:'operator',val:';'}] },
                { text: '}', tokens: [{type:'operator',val:'}'}] },
            ]
        }
    },
    {
        id: 'bfs',
        name: 'Breadth-First Search',
        category: 'Graph',
        difficulty: 'Medium',
        time: 'O(V + E)',
        description: 'Traverse a graph level by level, visiting all neighbors before moving to the next depth level.',
        keywords: ['bfs', 'breadth first', 'graph', 'traversal', 'queue', 'level order', 'neighbors'],
        vizType: 'graph',
        vizData: [[0,1],[0,2],[1,3],[1,4],[2,5],[2,6]],
        code: {
            python: [
                { text: 'from collections import deque', tokens: [{type:'keyword',val:'from '},{type:'variable',val:'collections'},{type:'keyword',val:' import '},{type:'type',val:'deque'}] },
                { text: '', tokens: [] },
                { text: 'def bfs(graph, start):', tokens: [{type:'keyword',val:'def'},{type:'function',val:' bfs'},{type:'operator',val:'('},{type:'param',val:'graph'},{type:'operator',val:', '},{type:'param',val:'start'},{type:'operator',val:'):'}] },
                { text: '    visited = set()', tokens: [{type:'variable',val:'    visited'},{type:'operator',val:' = '},{type:'builtin',val:'set'},{type:'operator',val:'()'}] },
                { text: '    queue = deque([start])', tokens: [{type:'variable',val:'    queue'},{type:'operator',val:' = '},{type:'type',val:'deque'},{type:'operator',val:'(['},{type:'variable',val:'start'},{type:'operator',val:'])'}] },
                { text: '    visited.add(start)', tokens: [{type:'variable',val:'    visited'},{type:'method',val:'.add'},{type:'operator',val:'('},{type:'variable',val:'start'},{type:'operator',val:')'}] },
                { text: '', tokens: [] },
                { text: '    while queue:', tokens: [{type:'keyword',val:'    while '},{type:'variable',val:'queue'},{type:'operator',val:':'}] },
                { text: '        node = queue.popleft()', tokens: [{type:'variable',val:'        node'},{type:'operator',val:' = '},{type:'variable',val:'queue'},{type:'method',val:'.popleft'},{type:'operator',val:'()'}] },
                { text: '        for neighbor in graph[node]:', tokens: [{type:'keyword',val:'        for '},{type:'variable',val:'neighbor'},{type:'keyword',val:' in '},{type:'variable',val:'graph'},{type:'operator',val:'['},{type:'variable',val:'node'},{type:'operator',val:']:'}] },
                { text: '            if neighbor not in visited:', tokens: [{type:'keyword',val:'            if '},{type:'variable',val:'neighbor'},{type:'keyword',val:' not in '},{type:'variable',val:'visited'},{type:'operator',val:':'}] },
                { text: '                visited.add(neighbor)', tokens: [{type:'variable',val:'                visited'},{type:'method',val:'.add'},{type:'operator',val:'('},{type:'variable',val:'neighbor'},{type:'operator',val:')'}] },
                { text: '                queue.append(neighbor)', tokens: [{type:'variable',val:'                queue'},{type:'method',val:'.append'},{type:'operator',val:'('},{type:'variable',val:'neighbor'},{type:'operator',val:')'}] },
            ],
            javascript: [
                { text: 'function bfs(graph, start) {', tokens: [{type:'keyword',val:'function'},{type:'function',val:' bfs'},{type:'operator',val:'('},{type:'param',val:'graph'},{type:'operator',val:', '},{type:'param',val:'start'},{type:'operator',val:') {'}] },
                { text: '    const visited = new Set();', tokens: [{type:'keyword',val:'    const '},{type:'variable',val:'visited'},{type:'operator',val:' = '},{type:'keyword',val:'new '},{type:'type',val:'Set'},{type:'operator',val:'();'}] },
                { text: '    const queue = [start];', tokens: [{type:'keyword',val:'    const '},{type:'variable',val:'queue'},{type:'operator',val:' = ['},{type:'variable',val:'start'},{type:'operator',val:'];'}] },
                { text: '    visited.add(start);', tokens: [{type:'variable',val:'    visited'},{type:'method',val:'.add'},{type:'operator',val:'('},{type:'variable',val:'start'},{type:'operator',val:');'}] },
                { text: '', tokens: [] },
                { text: '    while (queue.length > 0) {', tokens: [{type:'keyword',val:'    while '},{type:'operator',val:'('},{type:'variable',val:'queue'},{type:'operator',val:'.length > '},{type:'number',val:'0'},{type:'operator',val:') {'}] },
                { text: '        const node = queue.shift();', tokens: [{type:'keyword',val:'        const '},{type:'variable',val:'node'},{type:'operator',val:' = '},{type:'variable',val:'queue'},{type:'method',val:'.shift'},{type:'operator',val:'();'}] },
                { text: '        for (const neighbor of graph[node]) {', tokens: [{type:'keyword',val:'        for '},{type:'operator',val:'('},{type:'keyword',val:'const '},{type:'variable',val:'neighbor'},{type:'keyword',val:' of '},{type:'variable',val:'graph'},{type:'operator',val:'['},{type:'variable',val:'node'},{type:'operator',val:']) {'}] },
                { text: '            if (!visited.has(neighbor)) {', tokens: [{type:'keyword',val:'            if '},{type:'operator',val:'(!'},{type:'variable',val:'visited'},{type:'method',val:'.has'},{type:'operator',val:'('},{type:'variable',val:'neighbor'},{type:'operator',val:')) {'}] },
                { text: '                visited.add(neighbor);', tokens: [{type:'variable',val:'                visited'},{type:'method',val:'.add'},{type:'operator',val:'('},{type:'variable',val:'neighbor'},{type:'operator',val:');'}] },
                { text: '                queue.push(neighbor);', tokens: [{type:'variable',val:'                queue'},{type:'method',val:'.push'},{type:'operator',val:'('},{type:'variable',val:'neighbor'},{type:'operator',val:');'}] },
                { text: '            }', tokens: [{type:'operator',val:'            }'}] },
                { text: '        }', tokens: [{type:'operator',val:'        }'}] },
                { text: '    }', tokens: [{type:'operator',val:'    }'}] },
                { text: '}', tokens: [{type:'operator',val:'}'}] },
            ],
            java: [
                { text: 'public void bfs(Map<Integer, List<Integer>> graph, int start) {', tokens: [{type:'keyword',val:'public void'},{type:'function',val:' bfs'},{type:'operator',val:'('},{type:'type',val:'Map'},{type:'operator',val:'<'},{type:'type',val:'Integer'},{type:'operator',val:', '},{type:'type',val:'List'},{type:'operator',val:'<'},{type:'type',val:'Integer'},{type:'operator',val:'>> '},{type:'param',val:'graph'},{type:'operator',val:', '},{type:'type',val:'int '},{type:'param',val:'start'},{type:'operator',val:') {'}] },
                { text: '    Set<Integer> visited = new HashSet<>();', tokens: [{type:'type',val:'Set'},{type:'operator',val:'<'},{type:'type',val:'Integer'},{type:'operator',val:'> '},{type:'variable',val:'visited'},{type:'operator',val:' = '},{type:'keyword',val:'new '},{type:'type',val:'HashSet'},{type:'operator',val:'<>();'}] },
                { text: '    Queue<Integer> queue = new LinkedList<>();', tokens: [{type:'type',val:'Queue'},{type:'operator',val:'<'},{type:'type',val:'Integer'},{type:'operator',val:'> '},{type:'variable',val:'queue'},{type:'operator',val:' = '},{type:'keyword',val:'new '},{type:'type',val:'LinkedList'},{type:'operator',val:'<>();'}] },
                { text: '    queue.add(start);', tokens: [{type:'variable',val:'    queue'},{type:'method',val:'.add'},{type:'operator',val:'('},{type:'variable',val:'start'},{type:'operator',val:');'}] },
                { text: '    visited.add(start);', tokens: [{type:'variable',val:'    visited'},{type:'method',val:'.add'},{type:'operator',val:'('},{type:'variable',val:'start'},{type:'operator',val:');'}] },
                { text: '', tokens: [] },
                { text: '    while (!queue.isEmpty()) {', tokens: [{type:'keyword',val:'    while '},{type:'operator',val:'(!'},{type:'variable',val:'queue'},{type:'method',val:'.isEmpty'},{type:'operator',val:'()) {'}] },
                { text: '        int node = queue.poll();', tokens: [{type:'keyword',val:'        int '},{type:'variable',val:'node'},{type:'operator',val:' = '},{type:'variable',val:'queue'},{type:'method',val:'.poll'},{type:'operator',val:'();'}] },
                { text: '        for (int neighbor : graph.get(node)) {', tokens: [{type:'keyword',val:'        for '},{type:'operator',val:'('},{type:'type',val:'int '},{type:'variable',val:'neighbor'},{type:'operator',val:' : '},{type:'variable',val:'graph'},{type:'method',val:'.get'},{type:'operator',val:'('},{type:'variable',val:'node'},{type:'operator',val:')) {'}] },
                { text: '            if (!visited.contains(neighbor)) {', tokens: [{type:'keyword',val:'            if '},{type:'operator',val:'(!'},{type:'variable',val:'visited'},{type:'method',val:'.contains'},{type:'operator',val:'('},{type:'variable',val:'neighbor'},{type:'operator',val:')) {'}] },
                { text: '                visited.add(neighbor);', tokens: [{type:'variable',val:'                visited'},{type:'method',val:'.add'},{type:'operator',val:'('},{type:'variable',val:'neighbor'},{type:'operator',val:');'}] },
                { text: '                queue.add(neighbor);', tokens: [{type:'variable',val:'                queue'},{type:'method',val:'.add'},{type:'operator',val:'('},{type:'variable',val:'neighbor'},{type:'operator',val:');'}] },
                { text: '            }', tokens: [{type:'operator',val:'            }'}] },
                { text: '        }', tokens: [{type:'operator',val:'        }'}] },
                { text: '    }', tokens: [{type:'operator',val:'    }'}] },
                { text: '}', tokens: [{type:'operator',val:'}'}] },
            ]
        }
    },
    {
        id: 'dfs',
        name: 'Depth-First Search',
        category: 'Graph',
        difficulty: 'Medium',
        time: 'O(V + E)',
        description: 'Traverse a graph by going as deep as possible along each branch before backtracking.',
        keywords: ['dfs', 'depth first', 'graph', 'traversal', 'stack', 'backtracking', 'recursive'],
        vizType: 'graph',
        vizData: [[0,1],[0,2],[1,3],[1,4],[2,5],[2,6]],
        code: {
            python: [
                { text: 'def dfs(graph, node, visited=None):', tokens: [{type:'keyword',val:'def'},{type:'function',val:' dfs'},{type:'operator',val:'('},{type:'param',val:'graph'},{type:'operator',val:', '},{type:'param',val:'node'},{type:'operator',val:', '},{type:'param',val:'visited'},{type:'operator',val:'='},{type:'keyword',val:'None'},{type:'operator',val:'):'}] },
                { text: '    if visited is None:', tokens: [{type:'keyword',val:'    if '},{type:'variable',val:'visited'},{type:'keyword',val:' is '},{type:'keyword',val:'None'},{type:'operator',val:':'}] },
                { text: '        visited = set()', tokens: [{type:'variable',val:'        visited'},{type:'operator',val:' = '},{type:'builtin',val:'set'},{type:'operator',val:'()'}] },
                { text: '    visited.add(node)', tokens: [{type:'variable',val:'    visited'},{type:'method',val:'.add'},{type:'operator',val:'('},{type:'variable',val:'node'},{type:'operator',val:')'}] },
                { text: '    print(node)', tokens: [{type:'builtin',val:'    print'},{type:'operator',val:'('},{type:'variable',val:'node'},{type:'operator',val:')'}] },
                { text: '    for neighbor in graph[node]:', tokens: [{type:'keyword',val:'    for '},{type:'variable',val:'neighbor'},{type:'keyword',val:' in '},{type:'variable',val:'graph'},{type:'operator',val:'['},{type:'variable',val:'node'},{type:'operator',val:']:'}] },
                { text: '        if neighbor not in visited:', tokens: [{type:'keyword',val:'        if '},{type:'variable',val:'neighbor'},{type:'keyword',val:' not in '},{type:'variable',val:'visited'},{type:'operator',val:':'}] },
                { text: '            dfs(graph, neighbor, visited)', tokens: [{type:'function',val:'            dfs'},{type:'operator',val:'('},{type:'variable',val:'graph'},{type:'operator',val:', '},{type:'variable',val:'neighbor'},{type:'operator',val:', '},{type:'variable',val:'visited'},{type:'operator',val:')'}] },
            ],
            javascript: [
                { text: 'function dfs(graph, node, visited = new Set()) {', tokens: [{type:'keyword',val:'function'},{type:'function',val:' dfs'},{type:'operator',val:'('},{type:'param',val:'graph'},{type:'operator',val:', '},{type:'param',val:'node'},{type:'operator',val:', '},{type:'param',val:'visited'},{type:'operator',val:' = '},{type:'keyword',val:'new '},{type:'type',val:'Set'},{type:'operator',val:'()) {'}] },
                { text: '    visited.add(node);', tokens: [{type:'variable',val:'    visited'},{type:'method',val:'.add'},{type:'operator',val:'('},{type:'variable',val:'node'},{type:'operator',val:');'}] },
                { text: '    console.log(node);', tokens: [{type:'type',val:'    console'},{type:'method',val:'.log'},{type:'operator',val:'('},{type:'variable',val:'node'},{type:'operator',val:');'}] },
                { text: '    for (const neighbor of graph[node]) {', tokens: [{type:'keyword',val:'    for '},{type:'operator',val:'('},{type:'keyword',val:'const '},{type:'variable',val:'neighbor'},{type:'keyword',val:' of '},{type:'variable',val:'graph'},{type:'operator',val:'['},{type:'variable',val:'node'},{type:'operator',val:']) {'}] },
                { text: '        if (!visited.has(neighbor)) {', tokens: [{type:'keyword',val:'            if '},{type:'operator',val:'(!'},{type:'variable',val:'visited'},{type:'method',val:'.has'},{type:'operator',val:'('},{type:'variable',val:'neighbor'},{type:'operator',val:')) {'}] },
                { text: '            dfs(graph, neighbor, visited);', tokens: [{type:'function',val:'                dfs'},{type:'operator',val:'('},{type:'variable',val:'graph'},{type:'operator',val:', '},{type:'variable',val:'neighbor'},{type:'operator',val:', '},{type:'variable',val:'visited'},{type:'operator',val:');'}] },
                { text: '        }', tokens: [{type:'operator',val:'            }'}] },
                { text: '    }', tokens: [{type:'operator',val:'        }'}] },
                { text: '}', tokens: [{type:'operator',val:'    }'}] },
            ],
            java: [
                { text: 'public void dfs(Map<Integer, List<Integer>> graph, int node, Set<Integer> visited) {', tokens: [{type:'keyword',val:'public void'},{type:'function',val:' dfs'},{type:'operator',val:'('},{type:'type',val:'Map'},{type:'operator',val:'<'},{type:'type',val:'Integer'},{type:'operator',val:', '},{type:'type',val:'List'},{type:'operator',val:'<'},{type:'type',val:'Integer'},{type:'operator',val:'>> '},{type:'param',val:'graph'},{type:'operator',val:', '},{type:'type',val:'int '},{type:'param',val:'node'},{type:'operator',val:', '},{type:'type',val:'Set'},{type:'operator',val:'<'},{type:'type',val:'Integer'},{type:'operator',val:'> '},{type:'param',val:'visited'},{type:'operator',val:') {'}] },
                { text: '    visited.add(node);', tokens: [{type:'variable',val:'    visited'},{type:'method',val:'.add'},{type:'operator',val:'('},{type:'variable',val:'node'},{type:'operator',val:');'}] },
                { text: '    System.out.println(node);', tokens: [{type:'type',val:'    System.out'},{type:'method',val:'.println'},{type:'operator',val:'('},{type:'variable',val:'node'},{type:'operator',val:');'}] },
                { text: '    for (int neighbor : graph.get(node)) {', tokens: [{type:'keyword',val:'    for '},{type:'operator',val:'('},{type:'type',val:'int '},{type:'variable',val:'neighbor'},{type:'operator',val:' : '},{type:'variable',val:'graph'},{type:'method',val:'.get'},{type:'operator',val:'('},{type:'variable',val:'node'},{type:'operator',val:')) {'}] },
                { text: '        if (!visited.contains(neighbor)) {', tokens: [{type:'keyword',val:'            if '},{type:'operator',val:'(!'},{type:'variable',val:'visited'},{type:'method',val:'.contains'},{type:'operator',val:'('},{type:'variable',val:'neighbor'},{type:'operator',val:')) {'}] },
                { text: '            dfs(graph, neighbor, visited);', tokens: [{type:'function',val:'                dfs'},{type:'operator',val:'('},{type:'variable',val:'graph'},{type:'operator',val:', '},{type:'variable',val:'neighbor'},{type:'operator',val:', '},{type:'variable',val:'visited'},{type:'operator',val:');'}] },
                { text: '        }', tokens: [{type:'operator',val:'            }'}] },
                { text: '    }', tokens: [{type:'operator',val:'        }'}] },
                { text: '}', tokens: [{type:'operator',val:'    }'}] },
            ]
        }
    },
    {
        id: 'insertion-sort',
        name: 'Insertion Sort',
        category: 'Sorting',
        difficulty: 'Easy',
        time: 'O(n²)',
        description: 'Build the sorted array one element at a time by inserting each element into its correct position.',
        keywords: ['insertion sort', 'sort', 'insert', 'shift', 'ordering', 'partial'],
        vizType: 'sort',
        vizData: [12, 11, 13, 5, 6],
        code: {
            python: [
                { text: 'def insertion_sort(arr):', tokens: [{type:'keyword',val:'def'},{type:'function',val:' insertion_sort'},{type:'operator',val:'('},{type:'param',val:'arr'},{type:'operator',val:'):'}] },
                { text: '    for i in range(1, len(arr)):', tokens: [{type:'keyword',val:'    for '},{type:'variable',val:'i'},{type:'keyword',val:' in '},{type:'builtin',val:'range'},{type:'operator',val:'('},{type:'number',val:'1'},{type:'operator',val:', '},{type:'builtin',val:'len'},{type:'operator',val:'('},{type:'variable',val:'arr'},{type:'operator',val:'):'},{type:'operator',val:')'}] },
                { text: '        key = arr[i]', tokens: [{type:'variable',val:'        key'},{type:'operator',val:' = '},{type:'variable',val:'arr'},{type:'operator',val:'['},{type:'variable',val:'i'},{type:'operator',val:']'}] },
                { text: '        j = i - 1', tokens: [{type:'variable',val:'        j'},{type:'operator',val:' = '},{type:'variable',val:'i'},{type:'operator',val:' - '},{type:'number',val:'1'}] },
                { text: '        while j >= 0 and arr[j] > key:', tokens: [{type:'keyword',val:'        while '},{type:'variable',val:'j'},{type:'operator',val:' >= '},{type:'number',val:'0'},{type:'keyword',val:' and '},{type:'variable',val:'arr'},{type:'operator',val:'['},{type:'variable',val:'j'},{type:'operator',val:'] > '},{type:'variable',val:'key'},{type:'operator',val:':'}] },
                { text: '            arr[j + 1] = arr[j]', tokens: [{type:'variable',val:'            arr'},{type:'operator',val:'['},{type:'variable',val:'j'},{type:'operator',val:' + '},{type:'number',val:'1'},{type:'operator',val:'] = '},{type:'variable',val:'arr'},{type:'operator',val:'['},{type:'variable',val:'j'},{type:'operator',val:']'}] },
                { text: '            j -= 1', tokens: [{type:'variable',val:'            j'},{type:'operator',val:' -= '},{type:'number',val:'1'}] },
                { text: '        arr[j + 1] = key', tokens: [{type:'variable',val:'        arr'},{type:'operator',val:'['},{type:'variable',val:'j'},{type:'operator',val:' + '},{type:'number',val:'1'},{type:'operator',val:'] = '},{type:'variable',val:'key'}] },
                { text: '    return arr', tokens: [{type:'keyword',val:'    return '},{type:'variable',val:'arr'}] },
            ],
            javascript: [
                { text: 'function insertionSort(arr) {', tokens: [{type:'keyword',val:'function'},{type:'function',val:' insertionSort'},{type:'operator',val:'('},{type:'param',val:'arr'},{type:'operator',val:') {'}] },
                { text: '    for (let i = 1; i < arr.length; i++) {', tokens: [{type:'keyword',val:'    for '},{type:'operator',val:'('},{type:'keyword',val:'let '},{type:'variable',val:'i'},{type:'operator',val:' = '},{type:'number',val:'1'},{type:'operator',val:'; '},{type:'variable',val:'i'},{type:'operator',val:' < '},{type:'variable',val:'arr'},{type:'operator',val:'.length; '},{type:'variable',val:'i'},{type:'operator',val:'++) {'}] },
                { text: '        const key = arr[i];', tokens: [{type:'keyword',val:'        const '},{type:'variable',val:'key'},{type:'operator',val:' = '},{type:'variable',val:'arr'},{type:'operator',val:'['},{type:'variable',val:'i'},{type:'operator',val:'];'}] },
                { text: '        let j = i - 1;', tokens: [{type:'keyword',val:'        let '},{type:'variable',val:'j'},{type:'operator',val:' = '},{type:'variable',val:'i'},{type:'operator',val:' - '},{type:'number',val:'1'},{type:'operator',val:';'}] },
                { text: '        while (j >= 0 && arr[j] > key) {', tokens: [{type:'keyword',val:'        while '},{type:'operator',val:'('},{type:'variable',val:'j'},{type:'operator',val:' >= '},{type:'number',val:'0'},{type:'operator',val:' && '},{type:'variable',val:'arr'},{type:'operator',val:'['},{type:'variable',val:'j'},{type:'operator',val:'] > '},{type:'variable',val:'key'},{type:'operator',val:') {'}] },
                { text: '            arr[j + 1] = arr[j];', tokens: [{type:'variable',val:'            arr'},{type:'operator',val:'['},{type:'variable',val:'j'},{type:'operator',val:' + '},{type:'number',val:'1'},{type:'operator',val:'] = '},{type:'variable',val:'arr'},{type:'operator',val:'['},{type:'variable',val:'j'},{type:'operator',val:'];'}] },
                { text: '            j--;', tokens: [{type:'variable',val:'            j'},{type:'operator',val:'--;'}] },
                { text: '        }', tokens: [{type:'operator',val:'        }'}] },
                { text: '        arr[j + 1] = key;', tokens: [{type:'variable',val:'        arr'},{type:'operator',val:'['},{type:'variable',val:'j'},{type:'operator',val:' + '},{type:'number',val:'1'},{type:'operator',val:'] = '},{type:'variable',val:'key'},{type:'operator',val:';'}] },
                { text: '    }', tokens: [{type:'operator',val:'    }'}] },
                { text: '    return arr;', tokens: [{type:'keyword',val:'    return '},{type:'variable',val:'arr'},{type:'operator',val:';'}] },
                { text: '}', tokens: [{type:'operator',val:'}'}] },
            ],
            java: [
                { text: 'public void insertionSort(int[] arr) {', tokens: [{type:'keyword',val:'public void'},{type:'function',val:' insertionSort'},{type:'operator',val:'('},{type:'type',val:'int'},{type:'operator',val:'[] '},{type:'param',val:'arr'},{type:'operator',val:') {'}] },
                { text: '    for (int i = 1; i < arr.length; i++) {', tokens: [{type:'keyword',val:'    for '},{type:'operator',val:'('},{type:'type',val:'int '},{type:'variable',val:'i'},{type:'operator',val:' = '},{type:'number',val:'1'},{type:'operator',val:'; '},{type:'variable',val:'i'},{type:'operator',val:' < '},{type:'variable',val:'arr'},{type:'operator',val:'.length; '},{type:'variable',val:'i'},{type:'operator',val:'++) {'}] },
                { text: '        int key = arr[i];', tokens: [{type:'keyword',val:'        int '},{type:'variable',val:'key'},{type:'operator',val:' = '},{type:'variable',val:'arr'},{type:'operator',val:'['},{type:'variable',val:'i'},{type:'operator',val:'];'}] },
                { text: '        int j = i - 1;', tokens: [{type:'keyword',val:'        int '},{type:'variable',val:'j'},{type:'operator',val:' = '},{type:'variable',val:'i'},{type:'operator',val:' - '},{type:'number',val:'1'},{type:'operator',val:';'}] },
                { text: '        while (j >= 0 && arr[j] > key) {', tokens: [{type:'keyword',val:'        while '},{type:'operator',val:'('},{type:'variable',val:'j'},{type:'operator',val:' >= '},{type:'number',val:'0'},{type:'operator',val:' && '},{type:'variable',val:'arr'},{type:'operator',val:'['},{type:'variable',val:'j'},{type:'operator',val:'] > '},{type:'variable',val:'key'},{type:'operator',val:') {'}] },
                { text: '            arr[j + 1] = arr[j];', tokens: [{type:'variable',val:'            arr'},{type:'operator',val:'['},{type:'variable',val:'j'},{type:'operator',val:' + '},{type:'number',val:'1'},{type:'operator',val:'] = '},{type:'variable',val:'arr'},{type:'operator',val:'['},{type:'variable',val:'j'},{type:'operator',val:'];'}] },
                { text: '            j--;', tokens: [{type:'variable',val:'            j'},{type:'operator',val:'--;'}] },
                { text: '        }', tokens: [{type:'operator',val:'        }'}] },
                { text: '        arr[j + 1] = key;', tokens: [{type:'variable',val:'        arr'},{type:'operator',val:'['},{type:'variable',val:'j'},{type:'operator',val:' + '},{type:'number',val:'1'},{type:'operator',val:'] = '},{type:'variable',val:'key'},{type:'operator',val:';'}] },
                { text: '    }', tokens: [{type:'operator',val:'    }'}] },
                { text: '}', tokens: [{type:'operator',val:'}'}] },
            ]
        }
    },
    {
        id: 'quick-sort',
        name: 'Quick Sort',
        category: 'Sorting',
        difficulty: 'Medium',
        time: 'O(n log n)',
        description: 'Select a pivot element, partition the array around it, then recursively sort the partitions.',
        keywords: ['quick sort', 'sort', 'pivot', 'partition', 'divide and conquer', 'recursive'],
        vizType: 'sort',
        vizData: [10, 80, 30, 90, 40, 50, 70],
        code: {
            python: [
                { text: 'def quick_sort(arr, low, high):', tokens: [{type:'keyword',val:'def'},{type:'function',val:' quick_sort'},{type:'operator',val:'('},{type:'param',val:'arr'},{type:'operator',val:', '},{type:'param',val:'low'},{type:'operator',val:', '},{type:'param',val:'high'},{type:'operator',val:'):'}] },
                { text: '    if low < high:', tokens: [{type:'keyword',val:'    if '},{type:'variable',val:'low'},{type:'operator',val:' < '},{type:'variable',val:'high'},{type:'operator',val:':'}] },
                { text: '        pivot = partition(arr, low, high)', tokens: [{type:'variable',val:'        pivot'},{type:'operator',val:' = '},{type:'function',val:'partition'},{type:'operator',val:'('},{type:'variable',val:'arr'},{type:'operator',val:', '},{type:'variable',val:'low'},{type:'operator',val:', '},{type:'variable',val:'high'},{type:'operator',val:')'}] },
                { text: '        quick_sort(arr, low, pivot - 1)', tokens: [{type:'function',val:'        quick_sort'},{type:'operator',val:'('},{type:'variable',val:'arr'},{type:'operator',val:', '},{type:'variable',val:'low'},{type:'operator',val:', '},{type:'variable',val:'pivot'},{type:'operator',val:' - '},{type:'number',val:'1'},{type:'operator',val:')'}] },
                { text: '        quick_sort(arr, pivot + 1, high)', tokens: [{type:'function',val:'        quick_sort'},{type:'operator',val:'('},{type:'variable',val:'arr'},{type:'operator',val:', '},{type:'variable',val:'pivot'},{type:'operator',val:' + '},{type:'number',val:'1'},{type:'operator',val:', '},{type:'variable',val:'high'},{type:'operator',val:')'}] },
                { text: '', tokens: [] },
                { text: 'def partition(arr, low, high):', tokens: [{type:'keyword',val:'def'},{type:'function',val:' partition'},{type:'operator',val:'('},{type:'param',val:'arr'},{type:'operator',val:', '},{type:'param',val:'low'},{type:'operator',val:', '},{type:'param',val:'high'},{type:'operator',val:'):'}] },
                { text: '    pivot = arr[high]', tokens: [{type:'variable',val:'    pivot'},{type:'operator',val:' = '},{type:'variable',val:'arr'},{type:'operator',val:'['},{type:'variable',val:'high'},{type:'operator',val:']'}] },
                { text: '    i = low - 1', tokens: [{type:'variable',val:'    i'},{type:'operator',val:' = '},{type:'variable',val:'low'},{type:'operator',val:' - '},{type:'number',val:'1'}] },
                { text: '    for j in range(low, high):', tokens: [{type:'keyword',val:'    for '},{type:'variable',val:'j'},{type:'keyword',val:' in '},{type:'builtin',val:'range'},{type:'operator',val:'('},{type:'variable',val:'low'},{type:'operator',val:', '},{type:'variable',val:'high'},{type:'operator',val:'):'}] },
                { text: '        if arr[j] <= pivot:', tokens: [{type:'keyword',val:'        if '},{type:'variable',val:'arr'},{type:'operator',val:'['},{type:'variable',val:'j'},{type:'operator',val:'] <= '},{type:'variable',val:'pivot'},{type:'operator',val:':'}] },
                { text: '            i += 1', tokens: [{type:'variable',val:'            i'},{type:'operator',val:' += '},{type:'number',val:'1'}] },
                { text: '            arr[i], arr[j] = arr[j], arr[i]', tokens: [{type:'variable',val:'            arr'},{type:'operator',val:'['},{type:'variable',val:'i'},{type:'operator',val:']'},{type:'operator',val:', '},{type:'variable',val:'arr'},{type:'operator',val:'['},{type:'variable',val:'j'},{type:'operator',val:'] = '},{type:'variable',val:'arr'},{type:'operator',val:'['},{type:'variable',val:'j'},{type:'operator',val:']'},{type:'operator',val:', '},{type:'variable',val:'arr'},{type:'operator',val:'['},{type:'variable',val:'i'},{type:'operator',val:']'}] },
                { text: '    arr[i+1], arr[high] = arr[high], arr[i+1]', tokens: [{type:'variable',val:'    arr'},{type:'operator',val:'['},{type:'variable',val:'i'},{type:'operator',val:'+1]'},{type:'operator',val:', '},{type:'variable',val:'arr'},{type:'operator',val:'['},{type:'variable',val:'high'},{type:'operator',val:'] = '},{type:'variable',val:'arr'},{type:'operator',val:'['},{type:'variable',val:'high'},{type:'operator',val:']'},{type:'operator',val:', '},{type:'variable',val:'arr'},{type:'operator',val:'['},{type:'variable',val:'i'},{type:'operator',val:'+1]'}] },
                { text: '    return i + 1', tokens: [{type:'keyword',val:'    return '},{type:'variable',val:'i'},{type:'operator',val:' + '},{type:'number',val:'1'}] },
            ],
            javascript: [
                { text: 'function quickSort(arr, low = 0, high = arr.length - 1) {', tokens: [{type:'keyword',val:'function'},{type:'function',val:' quickSort'},{type:'operator',val:'('},{type:'param',val:'arr'},{type:'operator',val:', '},{type:'param',val:'low'},{type:'operator',val:' = '},{type:'number',val:'0'},{type:'operator',val:', '},{type:'param',val:'high'},{type:'operator',val:' = '},{type:'variable',val:'arr'},{type:'operator',val:'.length - '},{type:'number',val:'1'},{type:'operator',val:') {'}] },
                { text: '    if (low < high) {', tokens: [{type:'keyword',val:'    if '},{type:'operator',val:'('},{type:'variable',val:'low'},{type:'operator',val:' < '},{type:'variable',val:'high'},{type:'operator',val:') {'}] },
                { text: '        const pivot = partition(arr, low, high);', tokens: [{type:'keyword',val:'        const '},{type:'variable',val:'pivot'},{type:'operator',val:' = '},{type:'function',val:'partition'},{type:'operator',val:'('},{type:'variable',val:'arr'},{type:'operator',val:', '},{type:'variable',val:'low'},{type:'operator',val:', '},{type:'variable',val:'high'},{type:'operator',val:');'}] },
                { text: '        quickSort(arr, low, pivot - 1);', tokens: [{type:'function',val:'        quickSort'},{type:'operator',val:'('},{type:'variable',val:'arr'},{type:'operator',val:', '},{type:'variable',val:'low'},{type:'operator',val:', '},{type:'variable',val:'pivot'},{type:'operator',val:' - '},{type:'number',val:'1'},{type:'operator',val:');'}] },
                { text: '        quickSort(arr, pivot + 1, high);', tokens: [{type:'function',val:'        quickSort'},{type:'operator',val:'('},{type:'variable',val:'arr'},{type:'operator',val:', '},{type:'variable',val:'pivot'},{type:'operator',val:' + '},{type:'number',val:'1'},{type:'operator',val:', '},{type:'variable',val:'high'},{type:'operator',val:');'}] },
                { text: '    }', tokens: [{type:'operator',val:'    }'}] },
                { text: '}', tokens: [{type:'operator',val:'}'}] },
                { text: '', tokens: [] },
                { text: 'function partition(arr, low, high) {', tokens: [{type:'keyword',val:'function'},{type:'function',val:' partition'},{type:'operator',val:'('},{type:'param',val:'arr'},{type:'operator',val:', '},{type:'param',val:'low'},{type:'operator',val:', '},{type:'param',val:'high'},{type:'operator',val:') {'}] },
                { text: '    const pivot = arr[high];', tokens: [{type:'keyword',val:'    const '},{type:'variable',val:'pivot'},{type:'operator',val:' = '},{type:'variable',val:'arr'},{type:'operator',val:'['},{type:'variable',val:'high'},{type:'operator',val:'];'}] },
                { text: '    let i = low - 1;', tokens: [{type:'keyword',val:'    let '},{type:'variable',val:'i'},{type:'operator',val:' = '},{type:'variable',val:'low'},{type:'operator',val:' - '},{type:'number',val:'1'},{type:'operator',val:';'}] },
                { text: '    for (let j = low; j < high; j++) {', tokens: [{type:'keyword',val:'    for '},{type:'operator',val:'('},{type:'keyword',val:'let '},{type:'variable',val:'j'},{type:'operator',val:' = '},{type:'variable',val:'low'},{type:'operator',val:'; '},{type:'variable',val:'j'},{type:'operator',val:' < '},{type:'variable',val:'high'},{type:'operator',val:'; '},{type:'variable',val:'j'},{type:'operator',val:'++) {'}] },
                { text: '        if (arr[j] <= pivot) {', tokens: [{type:'keyword',val:'        if '},{type:'operator',val:'('},{type:'variable',val:'arr'},{type:'operator',val:'['},{type:'variable',val:'j'},{type:'operator',val:'] <= '},{type:'variable',val:'pivot'},{type:'operator',val:') {'}] },
                { text: '            i++;', tokens: [{type:'variable',val:'            i'},{type:'operator',val:'++;'}] },
                { text: '            [arr[i], arr[j]] = [arr[j], arr[i]];', tokens: [{type:'operator',val:'            ['},{type:'variable',val:'arr'},{type:'operator',val:'['},{type:'variable',val:'i'},{type:'operator',val:']'},{type:'operator',val:', '},{type:'variable',val:'arr'},{type:'operator',val:'['},{type:'variable',val:'j'},{type:'operator',val:']] = ['},{type:'variable',val:'arr'},{type:'operator',val:'['},{type:'variable',val:'j'},{type:'operator',val:']'},{type:'operator',val:', '},{type:'variable',val:'arr'},{type:'operator',val:'['},{type:'variable',val:'i'},{type:'operator',val:']];'}] },
                { text: '        }', tokens: [{type:'operator',val:'        }'}] },
                { text: '    }', tokens: [{type:'operator',val:'    }'}] },
                { text: '    [arr[i+1], arr[high]] = [arr[high], arr[i+1]];', tokens: [{type:'operator',val:'    ['},{type:'variable',val:'arr'},{type:'operator',val:'['},{type:'variable',val:'i'},{type:'operator',val:'+1]'},{type:'operator',val:', '},{type:'variable',val:'arr'},{type:'operator',val:'['},{type:'variable',val:'high'},{type:'operator',val:']] = ['},{type:'variable',val:'arr'},{type:'operator',val:'['},{type:'variable',val:'high'},{type:'operator',val:']'},{type:'operator',val:', '},{type:'variable',val:'arr'},{type:'operator',val:'['},{type:'variable',val:'i'},{type:'operator',val:'+1]];'}] },
                { text: '    return i + 1;', tokens: [{type:'keyword',val:'    return '},{type:'variable',val:'i'},{type:'operator',val:' + '},{type:'number',val:'1'},{type:'operator',val:';'}] },
                { text: '}', tokens: [{type:'operator',val:'}'}] },
            ],
            java: [
                { text: 'public void quickSort(int[] arr, int low, int high) {', tokens: [{type:'keyword',val:'public void'},{type:'function',val:' quickSort'},{type:'operator',val:'('},{type:'type',val:'int'},{type:'operator',val:'[] '},{type:'param',val:'arr'},{type:'operator',val:', '},{type:'type',val:'int '},{type:'param',val:'low'},{type:'operator',val:', '},{type:'type',val:'int '},{type:'param',val:'high'},{type:'operator',val:') {'}] },
                { text: '    if (low < high) {', tokens: [{type:'keyword',val:'    if '},{type:'operator',val:'('},{type:'variable',val:'low'},{type:'operator',val:' < '},{type:'variable',val:'high'},{type:'operator',val:') {'}] },
                { text: '        int pivot = partition(arr, low, high);', tokens: [{type:'keyword',val:'        int '},{type:'variable',val:'pivot'},{type:'operator',val:' = '},{type:'function',val:'partition'},{type:'operator',val:'('},{type:'variable',val:'arr'},{type:'operator',val:', '},{type:'variable',val:'low'},{type:'operator',val:', '},{type:'variable',val:'high'},{type:'operator',val:');'}] },
                { text: '        quickSort(arr, low, pivot - 1);', tokens: [{type:'function',val:'        quickSort'},{type:'operator',val:'('},{type:'variable',val:'arr'},{type:'operator',val:', '},{type:'variable',val:'low'},{type:'operator',val:', '},{type:'variable',val:'pivot'},{type:'operator',val:' - '},{type:'number',val:'1'},{type:'operator',val:');'}] },
                { text: '        quickSort(arr, pivot + 1, high);', tokens: [{type:'function',val:'        quickSort'},{type:'operator',val:'('},{type:'variable',val:'arr'},{type:'operator',val:', '},{type:'variable',val:'pivot'},{type:'operator',val:' + '},{type:'number',val:'1'},{type:'operator',val:', '},{type:'variable',val:'high'},{type:'operator',val:');'}] },
                { text: '    }', tokens: [{type:'operator',val:'    }'}] },
                { text: '}', tokens: [{type:'operator',val:'}'}] },
            ]
        }
    },
    {
        id: 'power-of-two',
        name: 'Power of Two',
        category: 'Bit Manipulation',
        difficulty: 'Easy',
        time: 'O(1)',
        description: 'Determine if a given integer is a power of two using bit manipulation.',
        keywords: ['power of two', 'bit manipulation', 'bitwise', 'n and n-1', 'binary'],
        vizType: 'binary',
        vizData: [16],
        code: {
            python: [
                { text: 'def is_power_of_two(n):', tokens: [{type:'keyword',val:'def'},{type:'function',val:' is_power_of_two'},{type:'operator',val:'('},{type:'param',val:'n'},{type:'operator',val:'):'}] },
                { text: '    return n > 0 and (n & (n - 1)) == 0', tokens: [{type:'keyword',val:'    return '},{type:'variable',val:'n'},{type:'operator',val:' > '},{type:'number',val:'0'},{type:'keyword',val:' and '},{type:'operator',val:'('},{type:'variable',val:'n'},{type:'operator',val:' & ('},{type:'variable',val:'n'},{type:'operator',val:' - '},{type:'number',val:'1'},{type:'operator',val:')) == '},{type:'number',val:'0'}] },
            ],
            javascript: [
                { text: 'function isPowerOfTwo(n) {', tokens: [{type:'keyword',val:'function'},{type:'function',val:' isPowerOfTwo'},{type:'operator',val:'('},{type:'param',val:'n'},{type:'operator',val:') {'}] },
                { text: '    return n > 0 && (n & (n - 1)) === 0;', tokens: [{type:'keyword',val:'    return '},{type:'variable',val:'n'},{type:'operator',val:' > '},{type:'number',val:'0'},{type:'operator',val:' && ('},{type:'variable',val:'n'},{type:'operator',val:' & ('},{type:'variable',val:'n'},{type:'operator',val:' - '},{type:'number',val:'1'},{type:'operator',val:')) === '},{type:'number',val:'0'},{type:'operator',val:';'}] },
                { text: '}', tokens: [{type:'operator',val:'}'}] },
            ],
            java: [
                { text: 'public boolean isPowerOfTwo(int n) {', tokens: [{type:'keyword',val:'public boolean'},{type:'function',val:' isPowerOfTwo'},{type:'operator',val:'('},{type:'type',val:'int '},{type:'param',val:'n'},{type:'operator',val:') {'}] },
                { text: '    return n > 0 && (n & (n - 1)) == 0;', tokens: [{type:'keyword',val:'    return '},{type:'variable',val:'n'},{type:'operator',val:' > '},{type:'number',val:'0'},{type:'operator',val:' && ('},{type:'variable',val:'n'},{type:'operator',val:' & ('},{type:'variable',val:'n'},{type:'operator',val:' - '},{type:'number',val:'1'},{type:'operator',val:')) == '},{type:'number',val:'0'},{type:'operator',val:';'}] },
                { text: '}', tokens: [{type:'operator',val:'}'}] },
            ]
        }
    }
];

const vizTypes = {
    'array': { icon: '📊', label: 'Array' },
    'array-pair': { icon: '🔗', label: 'Array Pair' },
    'sort': { icon: '📈', label: 'Sorting' },
    'tree': { icon: '🌳', label: 'Tree' },
    'linkedlist': { icon: '⛓️', label: 'Linked List' },
    'graph': { icon: '🕸️', label: 'Graph' },
    'binary': { icon: '💻', label: 'Binary' },
};
